class Page:
    url = ""
    content_page = ""
    load_time = ""
    # size_image = ""
    image_weight = ""
    # size_video = ""
    video_size = ""
    img_tags = ""
    video_tags = ""
    h1 = ""
    total_images = ""
    images_with_alt = ""
    top_words = ""
    top_keywords = ""

